#COMMON CONFIG
spring:
  main:
    banner-mode: off

  # DATABASE CONFIG
  datasource:
    url: jdbc:postgresql://localhost:5432/user_service
    username: postgres
    password: test
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    url: jdbc:postgresql://localhost:5432/user_service
    user: postgres
    password: test
    default-schema: public


# LOGGING CONFIG
logging:
  level:
    org:
      springframework:
        security: DEBUG


# SERVER CONFIG
server:
  port: 8080

# GRPC CONFIG
grpc:
  server:
    port: 6060
  client:
    authentication-service:
      address: localhost
      port: 6061
    role-service:

# INSTANCE CONFIG
instance:
  key: "user-service"
  id: 1





